# Build customization
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm64
# Archive customization
archives:
  - replacements:
      darwin: macos
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
